### ISSUE TITLE
Error when iterating over histogram with only zeros

### ISSUE THREAD

**Issue by luben** [HdrHistogram/HdrHistogram_rust#124]
If a histogram recorded only zeros, then the `iter_recorded` returns an empty iterator.

Reproduction:
```rust
use hdrhistogram::Histogram;
fn main() {
    let mut h = Histogram::<u64>::new(1).unwrap();
    h += 0;
    // Uncomment and suddenly the iterator returns 2 elements
    // h += 1;
    println!("Histogram: {h:?}");
    println!("Zeros: {}", h.count_at(0));
    // I expect that to return one element - 0 with count 1, or two if uncommented above
    for d in h.iter_recorded() {
        println!("{d:?}");
    }
}
```

It looks like the problem is with the iterator, as `count_at` returns the right number.

**Comment by jonhoo** [comment]
Good catch! I _think_ what's going on here is that we hit:
https://github.com/HdrHistogram/HdrHistogram_rust/blob/d56b823b66f06cc3617acaada9a828501fad4914/src/iterators/mod.rs#L188-L194

and `recorded::Iter` always returns `false` from `fn more`:

https://github.com/HdrHistogram/HdrHistogram_rust/blob/d56b823b66f06cc3617acaada9a828501fad4914/src/iterators/recorded.rs#L26-L28

What it probably needs to do instead is return `self.visited == Some(index_passed_in_to_more)` so that it will iterate over that first bin at least once. Could you test out that change and report back? 

If that doesn't work, then could you instrument [`PickyIterator::next`](https://github.com/HdrHistogram/HdrHistogram_rust/blob/d56b823b66f06cc3617acaada9a828501fad4914/src/iterators/mod.rs#L170) with some `dbg!` to see where it exits with `None` and what values cause the conditions that lead to that outcome?
