### ISSUE TITLE
Feature Request: Adding Sum to histograms

### ISSUE THREAD

**Issue by stemmr** [HdrHistogram/HdrHistogram_rust#132]
I have a use case where I would like to get an (approximate) sum of all the values in a histogram. Specifically I am looking at tracking the latency of calls in a `hdrhistogram` and then doing something like `histogram.sum()`. Although it looks like this can be achieved through [iter_recorded](https://docs.rs/hdrhistogram/latest/hdrhistogram/struct.Histogram.html#method.iter_recorded) I was wondering if there might be interest in having a dedicated method for this? (Happy to pick this up myself if there's interest!)

**Comment by jonhoo** [comment]
Hey there! It's an interesting idea, although I suspect you'll end up with having to decide on the semantics you want out of that call depending on the application/nature of the values. In particular, this is because the buckets record samples in a lossy way, such that the original sample value is not actually preserved. So your sum would end up being more like the count of each bucket times the bucket's range's mean, which is... odd. Alternatively we could keep a running sum of the recorded values, however that feels like a thing that could just as easily be tracked outside of the histogram and thus probably should be.

**Comment by stemmr** [comment]
Fair enough, I agree the semantics of having a sum in a lossy histogram is probably a bit sketch, it was pretty easy to pull together either way. Can take another look at adding these (approximate) aggregate metrics if more people run into this!
